### ISSUE TITLE
command doesn't work

### ISSUE THREAD

**Issue by thibault-ballof** [BryanLTU/bryan_airdrop#2]
Hi, i have an issue with this script : 
![Capture](https://user-images.githubusercontent.com/74681414/192803826-0bde352b-18f7-4b20-8fa7-9397ae47e83b.PNG)

i use ESX with weight system

**Comment by BryanLTU** [comment]
I believe your version of es_extended is too old for my script, because the way I made airdrops is by using imports.lua
